### ISSUE TITLE
Apotheosis conflict - min/max enchant level

### ISSUE THREAD

**Issue by kgibson9489** [PrinceOfAmber/Cyclic#1402]
Minecraft Version: 1.15.2

Forge Version: 31.1.46

Mod Version: 1.15.2-0.3.2

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):
Enchant levels 4-7 are unobtainable possibly due to an interaction with Apotheosis causing a math error, similar to the problem solved in another module in this issue: https://github.com/Lothrazar/Cyclic/issues/1255

I think the problem resides in enchant/XpEnchant.java and could be resolved in a similar way to issue #1255

Log file link:
https://pastebin.com/vDjzpnWi

**Comment by Lothrazar** [comment]
Should be fixed in 0.3.4 or higher can you check

**Comment by kgibson9489** [comment]
Thanks for the heads up, will test and report back

**Comment by kgibson9489** [comment]
Tested with 0.4.0 on Forge 31.1.63 and still getting the same problem unfortunately

**Comment by kornfan6589** [comment]
Tested with 0.4.1 on Forge 31.1.74 still getting math errors for experience boost. lvls 4-7

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2984937
