### ISSUE TITLE
Item User not working with Mystical agriculture watering cans in All the Mods 6 mod pack.

### ISSUE THREAD

**Issue by Fallensamurai94** [PrinceOfAmber/Cyclic#1590]
Minecraft Version: 1.16.4

Forge Version: 0.0.60

Mod Version: All the mods 6 (1.3.2c)
Single Player or Server: Server

Describe the problem (what you were doing; what happened; what should have happened): Item User not working with Mystical agriculture watering cans in All the Mods 6 mod pack. Had them working for about 2 days on the server by just placing down the item user in front of our crops and placing a filled Mystical agriculture watering can of any tier in it and turned it to always-on, then the other day they just stopped working tried replacing them tried crafting new ones but they just won't water with the Mystical agriculture watering cans. no mod updates and no mod addons have been done to my knowledge

Log file link: Owner is off for work

Video/images/gifs (direct upload or link):  N/A

Update: this issue seems to be reloving around "FTB chunks" claiming chucks if the item user is in one of the claimed chucks it stops working until the chunk in not claimed. why i don't know but it works in

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by briyoon** [comment]
Are the chunks that the item user is in claimed? I'm having trouble even after adding the fake cyclic users as allies with them right clicking bee hives with a scrapper. I noticed that fake user invite requests will sometimes reset but don't know if this is related.

**Comment by Fallensamurai94** [comment]
> Are the chunks that the item user is in claimed? I'm having trouble even after adding the fake cyclic users as allies with them right clicking bee hives with a scrapper. I noticed that fake user invite requests will sometimes reset but don't know if this is related.

I believed they stopped working after my friend and I claimed the chunks will unclaim them and try replacing them.

**Comment by Fallensamurai94** [comment]
Update: this issue seems to be reloving around "FTB chunks" claiming chucks if the item user is in one of the claimed chucks it stops working until the chunk in not claimed. why i don't know but it works in

**Comment by trunksbomb** [comment]
Possibly related to #1495 but that should have been fixed already.

**Comment by Fallensamurai94** [comment]
> Possibly related to #1495 but that should have been fixed already.

Can't be as we are still experiencing this issue with the most up to date version, and our server doesn't have an automated restart it's running 24/7

**Comment by trunksbomb** [comment]
By related I mean "these two issues may share a similar root cause" not "this issue is a duplicate of that issue". I see @briyoon mentioned adding the fake user to his allies, but did you? Since the User is a fake player, you have to add it to your ally list in FTB Chunks for it to work inside your claimed chunk.

**Comment by Lothrazar** [comment]
The watering can is returning  FAIL action type, from either here or a few lines below 

https://github.com/BlakeBr0/MysticalAgriculture/blob/f60de3510c694082acf5ff63299f119ab4a9d9a9/src/main/java/com/blakebr0/mysticalagriculture/item/WateringCanItem.java#L103

**Comment by Lothrazar** [comment]
My best guess is that the "canPlayerEdit" is returning false , saying the fake player is not allowed to edit here. need to think of a workaround

**Comment by Lothrazar** [comment]
doing some testing, https://www.curseforge.com/minecraft/mc-mods/gardening-tools and https://www.curseforge.com/minecraft/mc-mods/pickle-tweaks have a watering can that does work just fine in the auto user.  Ill try to add a hack to force Mystical Ags to work as well

**Comment by jonalange** [comment]
Is this fixed? For me it's still not working. It's still faster to use the watering can myself. So I don't know if it's just slower or not working at all in the Item User. Claimed chunks allow fake players and edit is set to public

**Comment by Beefyrulz** [comment]
I don't know anything about claimed chunks or not, but I got it work to by placing the item user underneath the tile I wanted it to be 'clicking' on, pointed upwards into the bottom of the block. Using the watering cans, you won't see the particles, but if you do it this way, it should work.
![2021-08-16_06 04 26_LI png](https://user-images.githubusercontent.com/89011537/129539486-e29d287a-ddea-4d63-aece-92090019d9e6.jpg)
![2021-08-16_06 04 09_LI](https://user-images.githubusercontent.com/89011537/129539490-737776d8-7881-4d62-930f-a2843a2982d1.jpg)
