### ISSUE TITLE
[1.18.2] Crushing Macerator not doing second Wither Rose recipe

### ISSUE THREAD

**Issue by Th3C0D3R** [PrinceOfAmber/Cyclic#2132]
Minecraft Version: 1.18.2

Forge Version: 1.18.2-forge-40.1.54

Mod Version: 1.18.2-1.7.2

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
Sooooo there is this Wither Rose thing which will result into 2 Soul Sand and 50% 2 Ghast Tears inside the Crushing Macerator. I hooked it up onto my AE Reactor and it does work but somehow I only get the first recipe.
It does not take 30s to make the second instead does the 5s recipe. 

Anything I am missing?

Log file link:

Video/images/gifs (direct upload or link): 
Crushing Macerator:
![grafik](https://user-images.githubusercontent.com/7798500/178710491-5685c720-9d14-4f26-a93d-2bbe39e7e98c.png)

Reactor:
![grafik](https://user-images.githubusercontent.com/7798500/178710645-2cd42460-cd0c-4690-8b83-fcaf8d675424.png)

Possible Recipes
![grafik](https://user-images.githubusercontent.com/7798500/178710863-c024980d-cd9f-4c19-87ff-fa705c872f62.png)

**Comment by Th3C0D3R** [comment]
As I saw in the source code there are two recipes for the wither rose. Maybe the second one which happens to be ghast tears and soulsand is either overwritten or ignored. 

I will removed the first recipe from the mod jar and loading it again with the hope of not breaking the mod and so fixing the problem

**Comment by Th3C0D3R** [comment]
so the problem is solved but only by removing the other recipie from the mod
I will let the Issue open so the creator/s know about that

**Comment by volrathstormborn** [comment]
> so the problem is solved but only by removing the other recipe from the mod I will let the Issue open so the creator/s know about that

This issue is back in the v1.10.2 version of the Direwolf20 18.2 pack.  Was working in v1.9.1
