### ISSUE TITLE
[Bug] [1.11.2] Uncrafting Grinder Pops Items

### ISSUE THREAD

**Issue by Calvin315** [PrinceOfAmber/Cyclic#307]
Hello,

After updating to the most recent version (1.1.4) of Cyclic for 1.11.2 and Cyclops Core (0.9.4), I noticed that the block begins to pop items out of its inventory. I have a hopper feeding into the block and another hopper under it pulling items. 
While it is uncrafting it seems to be shifting the stored item slot in the inventory right once after every one or two uncrafts. Eventually it no longer shifts and the item is ejected instead of being pulled out by the hopper. I saw this bug on MP but also happens on single-player.

Video of the bug:
https://youtu.be/B4wzZfqLxwY 

Thanks~

**Comment by PrinceOfAmber** [comment]
Thanks for the video! It should only spit items on the ground if the inventory is full so something is going off there

**Comment by PrinceOfAmber** [comment]
Releasing an update soon

**Comment by PrinceOfAmber** [comment]
Fixed in this release.  Let me know if anything else goes wrong https://minecraft.curseforge.com/projects/cyclic/files/2393324

**Comment by Calvin315** [comment]
Hmm... I haven't completed my testing but it seems like this is still occurring? Maybe upon every item uncraft check/refresh the inventory for the lowest empty spot. Hmm.

**Comment by PrinceOfAmber** [comment]
Issue occurred again, see https://github.com/PrinceOfAmber/Cyclic/issues/316

**Comment by Calvin315** [comment]
Hmm, it seems like it only screws up when there are hoppers attached to it... I tested this in vanilla forge singleplayer minecraft. 

I cannot narrow it down to the exact line of code but after looking at the testing, the bug only occurs when the item stack is completely extracted from the uncrafting grinder. This leads me to think since the last positions where the uncrafted materials were stored is != the current uncrafted materials, it moves on to the next spot. 

So if the machine's internal inventory is emptied out before the next uncraft cycle is completed, it moves on to the next slot in the internal inventory.

**Comment by Calvin315** [comment]
In this video, it seems like the after the slots that once held items have been emptied, it does not recognize that slot as valid anymore.

https://youtu.be/C8WeFWl37dk

**Comment by PrinceOfAmber** [comment]
Yes youre right. it works fine at first so it seems ok but after the first few slots are full, it THINKS everything is full. Sorry this took so long, working on it now

**Comment by PrinceOfAmber** [comment]
I left it running for a while to make sure it could fill up fully.  New fix seems to be sticking, let me know how it goes https://minecraft.curseforge.com/projects/cyclic/files/2396963
