### ISSUE TITLE
XP Pylon bug - "Deposit All" setting Level to -1, huge negative XpP values

### ISSUE THREAD

**Issue by LupusNoctis** [PrinceOfAmber/Cyclic#573]
Minecraft version & Mod Version: MC 1.12.2 (FTB Horizons 3 1.1.0 release)
Forge 14.23.0.2528
Cyclic v 1.12.2-1.9.8

Single player or Server: single player save

Describe problem (what you were doing / what happened): (after using the XP Pylon to deposit All XP)
- noticed I was not getting any XP bar progress from picking up Xp orbs, from mining, kills, nor animal breeding.  Checked my XP value from the EverlastingAbilities "totem" UI, said I had -5 XP total.
Checked values in NBTExplorer:
- had near overflow value for XpTotal
- XpLevel -1  ||  XpP: -4.294967E+08

Crash log (if any): does not cause crash
Issue easily reproduced in current save file, let me know if I can capture additional logging to help track issue.

**Comment by PrinceOfAmber** [comment]
I will check to see if this happens in Cyclic 1.9.10, i did just fix a bunch of Exp pylon issues in this latest release

**Comment by PrinceOfAmber** [comment]
This should have been fixed in 1.9.10, but i also added an extra safeguard in 1.9.11 to prevent this https://minecraft.curseforge.com/projects/cyclic/files/2499688

**Comment by yuri0r** [comment]
for some reason, this same issue still occurs in version 1.16.6 but exclusively on dedicated servers. 
tested with a forge server only running cyclic with default configs.
works perfectly fine on singleplayer worlds though.
